spring:
  h2:
    console:
      enable: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: true
security:
  jwt:
    validade: 30
    assinatura: 3d-Ynt-4BEz1mFQNFFbPTNVo68MgdlaqYlvgjHp8zLd7wmNlQdpGDLH9n1ZhvoJ_uY1Ssly6o1Jo9dSPrMK0-g