spring:
  datasource:
    url: jdbc:h2:~/databases/jalidb
    username: sa
    password: password
  h2:
    console:
      enable: false
      path: /h2
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    org:
      hibernate:
        pretty: TRACE
        SQL: debug
        type:
          descriptor:
            sql: trace

security:
  jwt:
    validade: 30
    assinatura: 3d-Ynt-4BEz1mFQNFFbPTNVo68MgdlaqYlvgjHp8zLd7wmNlQdpGDLH9n1ZhvoJ_uY1Ssly6o1Jo9dSPrMK0-g