INSERT INTO usuario (nome, login, senha, funcao) VALUES('Fulano', 'fulano', '$2a$10$6.aE5t3q4.RfwSHzm1nFDe4CeSVzkHbV7lpY3NKF6mW9SYFjZpp4O', 'USER');

INSERT INTO categoria (id, nome) VALUES(1, 'Aventura');
INSERT INTO categoria (id, nome) VALUES(2, 'Ciência');
INSERT INTO categoria (id, nome) VALUES(3, 'Drama');
INSERT INTO categoria (id, nome) VALUES(4, 'Ficção Científica');
INSERT INTO categoria (id, nome) VALUES(5, 'Graphic Novel');
INSERT INTO categoria (id, nome) VALUES(6, 'Mangá');
INSERT INTO categoria (id, nome) VALUES(7, 'Matemática');
INSERT INTO categoria (id, nome) VALUES(8, 'Romance');
INSERT INTO categoria (id, nome) VALUES(9, 'Horror');
INSERT INTO categoria (id, nome) VALUES(10, 'Fantasia');
INSERT INTO categoria (id, nome) VALUES(11, 'Ficção');
INSERT INTO categoria (id, nome) VALUES(12, 'Marketing');

INSERT INTO livro (id, nome, paginas, categoria_id) VALUES(1, 'Sandman: Edição Especial 30 Anos: Volume 3', 240, 5);
INSERT INTO livro (id, nome, paginas, categoria_id) VALUES(2, 'Imperfeitos', 256, 8);
INSERT INTO livro (id, nome, paginas, categoria_id) VALUES(3, 'Orgulho e Preconceito', 456, 3);
INSERT INTO livro (id, nome, paginas, categoria_id) VALUES(4, 'Ted Bundy: Um Estranho ao Meu Lado', 520, 3);
INSERT INTO livro (id, nome, paginas, categoria_id) VALUES(5, 'Death Note - Black Edition - Volume 2', 240, 6);
INSERT INTO livro (id, nome, paginas, categoria_id) VALUES(6, 'A Bomba', 476, 5);
INSERT INTO livro (id, nome, paginas, categoria_id) VALUES(7, 'Frankenstein', 304, 9);
INSERT INTO livro (id, nome, paginas, categoria_id) VALUES(8, 'Herdeiros de Atlântida - Filhos do Éden', 612, 10);
INSERT INTO livro (id, nome, paginas, categoria_id) VALUES(9, 'A Queda de Númenor: e outros contos da Segunda Era da Terra-média', 336, 10);
INSERT INTO livro (id, nome, paginas, categoria_id) VALUES(10, 'A revolução dos bichos: Um conto de fadas', 152, 4);
INSERT INTO livro (id, nome, paginas, categoria_id) VALUES(11, 'Ogiva', 220, 5);
INSERT INTO livro (id, nome, paginas, categoria_id) VALUES(12, 'O poderoso chefão', 496, 11);
INSERT INTO livro (id, nome, paginas, categoria_id) VALUES(13, 'Gatilhos Mentais: O Guia Completo com Estratégias de Negócios e Comunicações Provadas Para Você Aplicar', 144, 12);
INSERT INTO livro (id, nome, paginas, categoria_id) VALUES(14, 'Copywriting - Volume 1: O Método Centenário de Escrita Mais Cobiçado do Mercado Americano', 288, 12);
INSERT INTO livro (id, nome, paginas, categoria_id) VALUES(15, 'Storybrand: Crie mensagens claras e atraia a atenção dos clientes para sua marca', 240, 12);
INSERT INTO livro (id, nome, paginas, categoria_id) VALUES(16, 'Isso é marketing: Para ser visto é preciso aprender a enxergar ', 288, 12);
INSERT INTO livro (id, nome, paginas, categoria_id) VALUES(17, 'Tribos: Nós precisamos que vocês nos liderem', 160, 12);
INSERT INTO livro (id, nome, paginas, categoria_id) VALUES(18, 'Você ligou para o Sam', 336, 8);
INSERT INTO livro (id, nome, paginas, categoria_id) VALUES(19, 'O lado feio do amor', 336, 8);
INSERT INTO livro (id, nome, paginas, categoria_id) VALUES(20, 'É Assim que Acaba', 368, 8);
INSERT INTO livro (id, nome, paginas, categoria_id) VALUES(21, 'É Assim que Começa', 368, 8);